### PR TITLE
Add Algolia search for documentation. Need test in prod.

### PR DESCRIPTION
**Pull request by kiviok**
i'm just trying.)

### CODE REVIEW

**Comment by jvican** [comment]
Looks great! It seems that there are still no results coming from Algolia, some will at some point. In #1049 we discussed that the best place to add the search box is likely in the first menu bar (option 2 in the linked ticket). Could you move it there? I think it should be possible to add it there, but you may need to put it in https://github.com/scala/scala-lang as this repo only covers docs (tickets are spread out across both repos -- sorry for the confusion).

**Comment by kiviok** [comment]
i think option2 is not good edition. because then we will break main site layout by width.
header contains enough menu items to bring them closer together.

**Comment by s-pace** [comment]
The no result issue should be fixed. We needed an update of the configuration.

Attributes needed the "language" attribute to be set to "en" Solved by aae9cb6f81cde95af34b0d40d211359b4151e964

**Comment by jvican** [comment]
As a first step, I think the current approach (option 3) is enough, but I'd love to see the search box be used not only for docs but for the whole website, and that's why I think option 1 or 2 need to be implemented at some point so that users coming to the website can quickly type things in the search box.
  
Do you have a suggestion on what's the best place to add the search box so that it's used for both docs and blog posts/guides/other data? @kiviok 
  
Also, what are your thoughts @heathermiller ?

**Comment by kiviok** [comment]
First of all, all these pages need to be done in the same style. At least layout width. And then consider some option. Option2 then may be the better.

**Comment by jvican** [comment]
I'm fine merging this soon, but before that @kiviok could you modify the PR to be responsive? Here's a screenshot of the current state:
  
screenshot-2018-7-7 documentation scala documentation

**Comment by kiviok** [comment]
I have something like this now.

**Comment by jvican** [comment]
Excellent, let's give this a try!

**Comment by jvican** [comment]
By the way, thank you for this contribution @kiviok :smile:

**Comment by SethTisue** [comment]
really happy to have this, think you @kiviok

**Comment by kiviok** [comment]
@jvican @SethTisue you are welcome😉
this was my first PR) I really like scala, but at times there are difficulties. With jekyll I have a better situation😆
when ScalaDays arrive in Moscow? 🧐

**Comment by SethTisue** [comment]
> when ScalaDays arrive in Moscow?

heh, that's a tough one, I don't know. that decision normally gets made by the business folks. probably a hard sell since https://www.meetup.com/Scala-Moscow/events/past/ doesn't look too active

**Pull request merged**
