### PR TITLE
Bringing scalacourses' entry up to date

### PR DESCRIPTION
**Pull request by mslinn**
Resubmitting [the PR I made July 31](https://github.com/scala/scala-lang/pull/719) with this update, prior to docs.scala-lang.com was made public.

### CODE REVIEW

**Comment by mslinn** [comment]
All I want for Christmas is for this PR to be accepted

**Comment by mslinn** [comment]
@heathermiller This PR has been waiting for your review for 9 weeks. Please approve it.

**Comment by mslinn** [comment]
@SethTisue Since no-one is assigned to this task, and it lingers on, must this issue wait indefinitely for approval? If not, please help us and merge this PR now. If approval is unavoidable, and keeping in mind that Heather has not responded to this review request in 9 weeks, is there anyone else who can approve this PR right away?

This PR is a minor, bland, non-controversial change that is consistent with the rest of the page that it affects, but it is important to us. Such a listing would surely improve our year-end sales results. The is a direct correlation between the posting of this item and how our families will be fed this holiday season. Please help us by responding quickly.

**Comment by heathermiller** [comment]
It is controversial. See the history of the last PR you made to promote your classes to the doc site.

Please reduce the marketing and clearly state that the course is not free.

**Comment by heathermiller** [comment]
Also, it's clear that the repeated use of your URLs is a SEO optimization. Please don't play these tricks on scala-lang. One link is enough.

**Comment by mslinn** [comment]
I object to these comments and the previous comments. I believe that I have been and continue to be unfairly discriminated against. To date the product name and the company name have been suppressed and subject to censorship. Others have not been subject to these restrictions. This is unfair.

**Comment by SethTisue** [comment]
I agree with Heather.

**Comment by mslinn** [comment]
The only actionable changes requested are for a single link instead of a link to each course, and a mention that that the courses are not free.

I followed the Coursera example, which lists two courses and has a link to each. As I am sure you know, [the Coursera courses are not free](https://www.coursera.org/learn/progfun2?action=enroll#pricing), contrary to what is advertised. Coursera appears to be governed by different rules that what are being applied to me.

What is the definition of "marketing"? I am quoting the PR for convenience here, it reads as a simple factual description of the courses, without hype. What is objectionable about the following?

> ScalaCourses.com
> ScalaCourses.com has been dedicated to teaching Scala and Play Framework online since 2013. Enrollments are for 365 days, and during that time students can interact with instructors via email or screen sharing. Course material is continuously updated; enrolled students have access to all updates at no extra charge. GetScala.com describes the individual self-study and remote instructor-led training options.
> 
> Courses include:
> 
> Introduction to Scala
> Intermediate Scala
> Introduction to Play Framework for Scala

Where are the guidelines published that govern allowable postings?

**Comment by heathermiller** [comment]
The Coursera courses are indeed free. I have lost many of nights of sleep fighting with Coursera to keep all course materials free. Nothing is withheld between the paid and free version. Only difference is that if you pay, you get a certificate.

**Comment by mslinn** [comment]
Please accept this PR as is, or show me the guidelines that I am supposedly violating that Coursera is somehow complying with.

**Comment by SethTisue** [comment]
@mslinn this repo isn't governed by a 500-page written constitution covering every possible situation, and doubtless never will be... it's governed by consensus of the maintainers, in response to public feedback and discussion.

this PR will not be merged as is. we've given good-faith feedback on what version of it might be mergeable. if you become willing to make a good-faith effort to comply with that feedback, we can reopen this.

**Comment by mslinn** [comment]
Congratulations, @odersky

**Pull request closed without merging**
