### PR TITLE
Reorder and retitle the collection guides

### LINKED ISSUE #1365: Overviews page should make 2.13 collections standard, 2.12 extra
at the moment, it's still the reverse, https://docs.scala-lang.org/overviews/index.html has the 2.12 stuff at the top and not distinguished as being for an old version

### PR DESCRIPTION
**Pull request by dwijnand**
Fixes #1365

### CODE REVIEW

**Comment by SethTisue** [comment]
```
- ./_site/es/tour/annotations.html
335s
940
  *  External link https://www.scala-lang.org/api/current/scala/remote.html failed: 404 No error
335s
941
- ./_site/overviews/collections/trait-iterable.html
335s
942
  *  External link https://www.scala-lang.org/api/current/scala/collection/GenSetLike.html failed: 404 No error
```

**Comment by dwijnand** [comment]
I already fixed that in https://github.com/scala/docs.scala-lang/pull/1379, which was merged.

**Comment by dwijnand** [comment]
Let's do a rolling-restart on this PR and see if it gets a shiny green checkmark.

**Comment by SethTisue** [comment]
@jvican can you give Drone a kick in the pants?

**Comment by jvican** [comment]
Yup, working on it

**Comment by jvican** [comment]
@SethTisue @dwijnand  I've migrated this repo from platform-ci.scala-lang.org (which was running a CI instance of Drone 0.5) to ci.scala-lang.org (running a Drone 0.8 instance, the CI we use for Zinc and Bloop, which has higher uptime and less issues).

I've also made you both admins so now you should be able to do any changes in the UI. As I don't have permissions on this repo, I couldn't enable this repo in ci.scala-lang.org. Can either of you do it? Whenever it's enabled, everything should work.

**Comment by dwijnand** [comment]
Activated this repo in ci.scala-lang.org, and also made you admin of this repo.

**Comment by dwijnand** [comment]
Bouncing the PR to trigger CI

**Comment by dwijnand** [comment]
Deleted the platform-ci webhook (hopefully not a mistake)

**Comment by jvican** [comment]
Having a look at the CI right now, I'll take it from here @dwijnand :smile:

**Comment by jvican** [comment]
I've just pushed to master a commit to update the CI badge and it works https://ci.scala-lang.org/scala/docs.scala-lang/1/3
  
So it looks like when changing the CI, closing and opening again a pull request doesn't seem to trigger a request to the CI server? Maybe a GitHub issue?

Pushing again the commit should work.

**Comment by dwijnand** [comment]
Yeah a fresh SHA was my next step.

**Comment by dwijnand** [comment]
Gucci

**Comment by dwijnand** [comment]
Rebased onto #1389.

**Pull request merged**
