### PR TITLE
Update why-scala-3.md

### PR DESCRIPTION
**Pull request by jakedmlee**
a.filter(_ <  30).map(_ * 10) doesn't results in List(100, 200) but List(100, 200, 100).

### CODE REVIEW

**Review by xuwei-k — DISMISSED** [review]

**Comment by julienrf** [comment]
Are the two last commits intended to be part of this PR?

**Comment by jakedmlee** [comment]
> Are the two last commits intended to be part of this PR?

Not related to each other. But the GraalVM link address, https://www.graalvm.org/docs/reference-manual/scala/ doesn't exist.
During building PR, html-proofer is failed because of that link. (I think so.)
Many people trying to merge their code are being failed at this time. Check it out.
So for the success of checking html-proofer I removed this address.

**Review by Philippus — APPROVED** [review]

**Comment by jakedmlee** [comment]
Who are the maintainers to have write access to approve running workflows?  If you can see the button, Approve and run, put the button down.

**Comment by jakedmlee** [comment]
Who are the maintainers to have write access to approve running workflows? If you see the button, Approve and run, put the button down.

**Comment by Philippus** [comment]
I don't really see an alternative to the links either, so I'm going to merge this. We can always add better links later.

**Comment by SethTisue** [comment]
perhaps @chaitanyawaikar would like to follow up on the Graal link thing (PR was #1989)

**Pull request merged**
