### PR TITLE
Update futures.md (zh-cn)

### PR DESCRIPTION
**Pull request by corkine**
Updated some areas where the statement is unreasonable, and added some missing translations according to the English documentation.

### CODE REVIEW

**Comment by eed3si9n** [comment]
@corkine Thanks for the contribution!

I can't review this myself so could you find someone who can? /cc @liufengyun, @dongxuwang, @xingyif

**Comment by eed3si9n** [comment]
Also #1406 is awaiting review. Maybe you can review his?

**Comment by dongxuwang** [comment]
Ok, will do

**Comment by SethTisue** [comment]
@corkine interested in returning to this?

**Comment by corkine** [comment]
Sorry, I am a newbie, I will handle this.

**Pull request closed without merging**
