### PR TITLE
java.lang.ArrayIndexOutOfBoundsException: 0

### PR DESCRIPTION
**Pull request by Kobenko**

### CODE REVIEW

**Comment by SethTisue** [comment]
the intention here was that you pass a single argument on the command line when you run the app. if you don't pass one, you get the `ArrayIndexOutOfBoundsException`

I tend to agree, though, that it just distracts from the main idea of this part of the tour.

how about just `extends StringIterator("Scala")`? this avoids the unnecessary extra `val`, plus it's "Scala" not "SCALA"

**Comment by Kobenko** [comment]
Yes, passing a string value to an argument would be a good option

**Comment by Kobenko** [comment]
@SethTisue how often do you measure the branches? I have several more suggestions for improving the tour.

**Comment by SethTisue** [comment]
thank you for this!

merging PRs is done on no particular schedule by Heather, myself, and others. I usually don't merge things until they've been sitting for a few days, to allow time for community review and feedback.

there is certainly plenty of room for improvement left on the tour — looking forward to further suggestions and pull requests!

**Pull request merged**
