### PR TITLE
Fix errors in seq.md

### PR DESCRIPTION
**Pull request by artemkorsakov**
Mistake in `List("foo", "bar", "quux").distinctBy(_.length) == List("foo", "bar")`. 
Right: List("foo", "bar", "quux").distinctBy(_.length) ==  List("foo", "quux")

### CODE REVIEW

**Review by Philippus — APPROVED** [review]
nice catch!

**Comment by Philippus** [comment]
The build error looks not related to the PR, so I think this can be merged.

**Comment by artemkorsakov** [comment]
Yes, all pull requests after #1806 fail due to localization in the `zh-cn` language:
`- ./_site/zh-cn/overviews/reflection/typetags-manifests.html
  *  internally linking to /zh-cn/zh-cn/overviews/reflection/typetags-manifests.html, which does not exist (line 0)
     <a href="/zh-cn/zh-cn/overviews/reflection/typetags-manifests.html" class="lang">中文 (简体)</a>
htmlproofer 3.15.3 | Error:  HTML-Proofer found 1 failure!`

Do I still need to do something?
Or I just need to wait for the merge?

**Comment by Philippus** [comment]
I merged it, thank you!

**Pull request merged**
