### PR TITLE
Fixes broken layout of markdown tables

### PR DESCRIPTION
**Pull request by arata-honda**
I find some collapses table. I fix it

### CODE REVIEW

**Comment by eed3si9n** [comment]
"display collapses" is likely a mistranslation of 表示が崩れる. A broken layout would an appropriate translation iiuc.

@arata-honda Could you please post screenshots of before and after? I am guessing that the change is good, but on Chrome I don't see the layout to be broken.

**Comment by arata-honda** [comment]
@eed3si9n Sorry, it's no problem on chrome and macdown, but vscode is occured it

I put screen shot with vscode.

before(incompat-syntactic.md)
スクリーンショット 2021-11-29 23 07 09

after(incompat-syntactic.md)
スクリーンショット 2021-11-29 23 07 20

before(incompatibility-table.md )
スクリーンショット 2021-11-29 23 08 28

after(incompatibility-table.md )
スクリーンショット 2021-11-29 23 08 35

**Review by eed3si9n — APPROVED** [review]
LGTM

**Comment by eed3si9n** [comment]
@arata-honda That makes sense. Thanks for the clarification.

**Pull request merged**
