### PR TITLE
Update sample code for classes

### PR DESCRIPTION
**Pull request by calindragomir**
I think you might have a slight syntax error in the example.

### CODE REVIEW

**Comment by calindragomir** [comment]
Or is this intentional , based on https://docs.scala-lang.org/sips/trailing-commas.html ?
If so, I apologize for the noise.

**Comment by julienrf** [comment]
Yes, the code shown on the page is valid with Scala 2.12 or 2.13 (I don’t remember which one). I am not sure if we have a recommendation regarding the usage of trailing commas…

**Comment by calindragomir** [comment]
Ok, I just thought it looked a bit odd, even though it's valid.
I'm guessing the preferred choice for coders would be to omit the trailing comma, even if it works with it. And for that reason the sample code would have the clean version. But , it's just a guess 😄 .

Thanks for the reply.

**Comment by SethTisue** [comment]
Closing, but I think a new PR addressing the question about trailing commas would be welcome. I don't think there is a consensus on whether to use them in cases like this, so I don't think we should make a clear recommendation one way or the other; but it would be appropriate to note that the choice was conscious here but that tastes may differ.

**Pull request closed without merging**
