### PR TITLE
Fix a little bug in the example code

### PR DESCRIPTION
**Pull request by qiuyangnie**
The variable (a, b, c) in each case should be matched the variable printed out.

### CODE REVIEW

**Comment by SethTisue** [comment]
@qiuyangnie I agree this is an improvement. I wonder if it might actually be better more idiomatic to write `case a` all three times. the current code kind of gives the impression that you need to use a different name each time, but you don't.

wdyt?

**Comment by qiuyangnie** [comment]
I do agree with you! The earlier example in this chapter, however, should have demonstrated the 'variable name' in each `case` can be same. This example could provide an alternative way to demonstrate the 'variable name' in each `case` can be different.

**Comment by SethTisue** [comment]
I think that's a subtlety that would be lost on readers unless it was explicitly called out, and I don't think it's actually worth calling out, because using a different name each time doesn't actually make the code better; I think it's actually worse that way.

So I still suggest that the right fix here is simply:

> write `case a` all three times

**Comment by SethTisue** [comment]
(regardless: if you disagree or aren't interested in pursuing this farther, I'll hit "merge" anyway)

**Pull request merged**
