### PR TITLE
Fix htmlproofer errors

### PR DESCRIPTION
**Pull request by byeonggukgong**
According to #1113, CI occurred errors when merged PR #1106. I thought the problem is CI tried to find non existent files.

So, I try to fix the problem by adding tour-of-scala templates. :)

### CODE REVIEW

**Comment by byeonggukgong** [comment]
@SethTisue @jvican I fixed CI errors and now it works fine. The problem surfaced while CI was checking Chinese translation's all links validity.

**Comment by jvican** [comment]
Thank you @byeonggukgong, I appreciate this.
  
I cannot yet merge it because there are some conflicts, could you fix them, push again and I'll merge?

**Comment by jvican** [comment]
:tada: thank you!

**Comment by byeonggukgong** [comment]
@jvican I solved conflicts :) I think contributors need to focus CI results!

**Pull request merged**
