### PR TITLE
Update some compiler options

### PR DESCRIPTION
**Pull request by som-snytt**
Updated for a few major features.

It would be nice to automate or at least automatically verify.

### CODE REVIEW

**Review by julienrf — APPROVED** [review]
Thank you very much @som-snytt! The changes look good to me, but I would like someone from the Scala 3 compiler team to also have a look at them.

**Review by prolativ — APPROVED** [review]
If we want to keep things ordered alphabetically, then  `-Vdebug`, `-Vlog:<phases>` and `-Wself-implicit` should be moved. Otherwise LGTM

**Comment by som-snytt** [comment]
Improved alphabetic order, added new options (they keep adding options), removed old aliases as a matter of policy.

Checked order against `scalac -help`, `scalac -V`, etc.

Tragically, I moved `-V` and `-W` to the front and lost the useful diff. Sorry about that.

Worth motivating that order, aside from the alphabet. As a user, I want more info (`-V`) or maybe more safety (`-W`). If I'm an advanced user, I might use an advanced option (`-X`). In the privacy of my own home or cubicle, I might add a private option (`-Y`) if no one is looking over my shoulder.

**Comment by julienrf** [comment]
Thank you!

**Pull request merged**
