### PR TITLE
general link removed

### PR DESCRIPTION
**Pull request by xhudik**
General link to whole Scala 3 reference is misleading: https://github.com/scala/docs.scala-lang/issues/1948

### CODE REVIEW

**Comment by SethTisue** [comment]
I agree that the general link is not very helpful.

@alvinj is this the fix you'd prefer, though?

**Comment by alvinj** [comment]
> is this the fix you'd prefer

That’s a very interesting question. :) 

The initial plan/hope was to link to a more-complete “Reference” book, something like an online version of _Programming in Scala_. But it may be a long time before that happens.

Hmmm, I don’t see any other detailed info under docs.scala-lang.org ...

One option is to un-comment the comment on that page. I’d have to look at that to see how ugly that would be. We could also make it an appendix page, or I could donate one of these pages to make them an appendix as well:

* [How to use the Option/Some/None pattern](https://alvinalexander.com/scala/best-practice-option-some-none-pattern-scala-idioms/)
* [How to use higher-order functions (HOFs) with Option](https://alvinalexander.com/scala/how-use-higher-order-functions-option-some-none-match-expressions/)

(I’m going down this road because I think it will be a while before we can link to a Reference book on docs.scala-lang.org.)

All that being said, that link can be deleted because I don’t think there’s anything under the Dotty docs site for this. Also, it looks like this code at the bottom of that page should also be removed because it’s only referenced that one time:

```
[reference]: {{ site.scala3ref }}/overview.html
```

**Comment by b-studios** [comment]
I agree, deleting the link for now seems like the best option.

**Comment by xhudik** [comment]
ok, shoud be done now!

**Pull request merged**
