### PR TITLE
modified Chinese ca-context-bounds.md

### PR DESCRIPTION
**Pull request by benluo**

### CODE REVIEW

**Comment by sjrd** [comment]
Ping @scala/docs-zh.

**Review by dongxuwang — COMMENTED** [review]
please take a comparison if any help, thanks

**Comment by jxnu-liguobin** [comment]
ci complains

**Review by jxnu-liguobin — APPROVED** [review]

**Comment by SethTisue** [comment]
thank you @benluo and reviewers!

**Pull request merged**
