### PR TITLE
Updated following implementation experience in Typelevel Scala

### PR DESCRIPTION
**Pull request by milessabin**

### CODE REVIEW

**Comment by heathermiller** [comment]
cc/ @jvican

**Comment by jvican** [comment]
I've been summoned and I approve!

**Comment by smarter** [comment]
I see this got merged last week but http://docs.scala-lang.org/sips/pending/42.type.html is still out of date, how come?

**Comment by jvican** [comment]
That's the old link. New link is here: http://docs.scala-lang.org/sips/42.type.html.

**Comment by smarter** [comment]
Old one should be delete then, because if I google SIP 23 that's what I find.

**Pull request merged**
