### PR TITLE
SIP draft for pattern matching with named fields

### PR DESCRIPTION
**Pull request by Jentsch**

### CODE REVIEW

**Comment by Jentsch** [comment]
In my local build the new SIP doesn't show up in the sip overview. (sips/all.html)

**Review by RubenVerg — CHANGES_REQUESTED** [review]
Couple of typos: says to instead of two at line 49, double instead of double at line 66.

**Comment by Jentsch** [comment]
> Couple of typos: says to instead of two at line 49, double instead of double at line 66.

Thanks, is fixed now.

**Comment by SethTisue** [comment]
@julienrf should this be relocated to https://github.com/scala/improvement-proposals ?

**Comment by julienrf** [comment]
Yes, thank you for pinging me Seth.
@Jentsch, may I ask you to re-submit your proposal to the scala/improvement-proposals repo? The instructions are here: https://docs.scala-lang.org/sips/sip-tutorial.html

**Comment by Jentsch** [comment]
Here is the new PR: https://github.com/scala/improvement-proposals/pull/44

**Comment by julienrf** [comment]
Thank you!

**Pull request closed without merging**
