### PR TITLE
Update tuples.md

### PR DESCRIPTION
**Pull request by manishbansal8843**
Added missing statements

### CODE REVIEW

**Comment by SethTisue** [comment]
I don't see what this adds, since the values were already printed?

**Comment by manishbansal8843** [comment]
The values printed were part of scala REPL response. It does not show the usage as such.

**Comment by SethTisue** [comment]
I don't see that as a problem. (Anyone else watching the repo have an opinion?)

**Comment by SethTisue** [comment]
closing as I don't think this is mergeable as-is, but we could reopen if you want to revise it to take a different approach

**Comment by som-snytt** [comment]
It's still hacktoberfest, so this PR might still be relevant. I do see that the intention is to show that tuple deconstruction in a pattern actually creates variables you can use in the ordinary way. But I agree that a better example is needed. Like maybe using an `age` variable. The example `(x, y, z)` is not very meaningful except as coordinates. Arguably leaving no space after `val` is poor style.
```
scala> val(x, y, z) = (3, "Three", new Person("David"))
val x: Int = 3
val y: String = Three
val z: Person = Person(David)
```
It's also a missed opportunity to standardize on tupple or toople.

**Pull request closed without merging**
