### PR TITLE
[refactor] Extract duplicated card group to include.

### PR DESCRIPTION
**Pull request by dongxuwang**

### CODE REVIEW

**Comment by SethTisue** [comment]
@julienrf can you review, or suggest a reviewer?

**Comment by julienrf** [comment]
Thank you for the PR @dongxuwang. Could you please post a screenshot of the resulting pages in English, Japanese and Chinese?

**Comment by dongxuwang** [comment]
Screen Shot 2022-03-16 at 7 24 40 AM
Screen Shot 2022-03-16 at 7 24 28 AM
Screen Shot 2022-03-16 at 7 24 15 AM

**Comment by julienrf** [comment]
It looks like the card icons are lost in the English and Japanese versions. Could you please double check?

**Comment by dongxuwang** [comment]
> It looks like the card icons are lost in the English and Japanese versions. Could you please double check?

Sorry, probably because of the network at that time. Let me do it again

**Comment by dongxuwang** [comment]
Screen Shot 2022-03-16 at 5 28 55 PM
Screen Shot 2022-03-16 at 5 28 44 PM
Screen Shot 2022-03-16 at 5 28 31 PM

**Review by julienrf — APPROVED** [review]
Thank you!

**Pull request merged**
