### PR TITLE
Overhauled documentation site design and structure

### PR DESCRIPTION
**Pull request by travissarles**

### CODE REVIEW

**Comment by SethTisue** [comment]
built it locally — looks great!

I see the headers at the top are the scala-lang.org headers — does that mean this is intended to replace http://www.scala-lang.org/documentation/ ...?

**Comment by travissarles** [comment]
Thanks, @SethTisue! Yes, scala-lang.org/documentation will redirect to docs.scala-lang.org.

**Comment by heathermiller** [comment]
Todos before this can be merged
- [ ] Restore lost SIPs/SLIP pages
- [ ] Fix broken translation links on landing page
- [ ] Restore footer
- [ ] Restore Java to Scala guide
- [ ] Restore style guide
- [ ] Get rid of "what is Scala" on landing page 

...more forthcoming

**Comment by SethTisue** [comment]
superseded by #806

**Pull request closed without merging**
