### PR TITLE
Use https instead of http

### PR DESCRIPTION
**Pull request by komainu8**
Dear, developers.
I've fixed an issue #1459.

### CODE REVIEW

**Comment by exoego** [comment]
There is already your pull request https://github.com/scala/docs.scala-lang/pull/1471 addressing the issue #1459 
What is a reason to separate PRs?
I think an ordinal issue (not meta issue) should be addressed in single PR for most cases, so that reviewers close the issue after merge.

**Comment by komainu8** [comment]
@exoego Thank you for your comment.
I agree with you. I think I should put those pull request in one.

However, files that should modify the same as this pull request is many.

I think that is difficult to review all modify at once.
Therefore, I split one pull request by the one file.

If we should put all modify in one is better, I'll do so.

I'm sorry, I'm bad at English.
Is what I'm saying getting through to you properly?

**Comment by exoego** [comment]
Don't mind, it is clear what you are saying.

So, I guess you are afraid of broken links (404) that reviewers should take care, if replace all `http://` into `http://` at once ?
If so, please do not mind !!
There is a link checker in this repo, and verifies that all links is valid (with some exception for oracle.com) on pull requests.
If 404 found, you can find easily which links need some tweaks (e.g.:  there is no https://... for the domain).

So I suggest to
1. Replace all http:// to https:// and add all into single commit.
2. Push and watch link checker result.
3. If there are 404, fix them and create a new commit. So reviewers can spot only URLs that carefull review are required.

**Comment by komainu8** [comment]
Oh! That's a great mechanism.
Yes. I was afraid of broken links (404) that reviewers should take care of.

Thank you for your suggestion.
I'll accept your suggestion.

First, I'll close this PR.
Second, I replace all http:// to https:// and add all modify into #1471.
Third, I check links and repair broken links.

**Pull request closed without merging**
