### PR TITLE
Rewrote currying tour

### PR DESCRIPTION
**Pull request by travissarles**

### CODE REVIEW

**Comment by SethTisue** [comment]
I suggest renaming the whole section from "currying" to "multiple parameter lists", and never saying "curry" anywhere in the body text, either. Scala people don't normally talk about "currying".

I don't think you've chosen appropriate example code here — there is no good reason, that I can see anyway (and the text doesn't help me), to use multiple parameter lists for this function.

The old example code was unsatisfactory also.

I'd suggest looking for a commonly used method in the Scala standard library that has more than one parameter list. then show how use it, explain why it has multiple parameter lists, and then show how it could be defined. perhaps `foldLeft`?

**Comment by jvican** [comment]
Maybe we can let this open so that a contributor can pick it up?

**Comment by SethTisue** [comment]
Yes please, is there a volunteer who would like to get it over the finish line?

**Comment by jvican** [comment]
As you took the other one, I'll take this one.

**Comment by jvican** [comment]
As we got quite many volunteers, I'm gonna see if a volunteer dares to do this one! If there isn't one in two weeks, I'll take care of it :smile:.

**Comment by SethTisue** [comment]
replaced by #986

**Pull request closed without merging**
