### PR TITLE
Update Vector-class.md

### PR DESCRIPTION
**Pull request by manishbansal8843**
Corrected typo. Also changed operator from `++` to `++:` for consistency. It might be confusing for beginners.

### CODE REVIEW

**Comment by SethTisue** [comment]
I agree with the `List` to `Vector` change

I don't understand the motivation for changing `++` to `++:`?

**Comment by manishbansal8843** [comment]
As per API [documentation](https://www.scala-lang.org/api/current/scala/collection/immutable/Vector.html), `++` is an alias for `concat` where as `++:` is an alias for `prependedAll`. Since, the current documentation is talking about pre-pending all the elements to a vector, I feel it is more appropriate to use `++:` rather than `++` although result would be same.

**Comment by SethTisue** [comment]
I routinely see `++` in Scala code (in the books, in talks, etc) and I wasn't even aware `++:` existed. I think this is fine as-is.

I'd be happy to merge this if you reduce it to just the `List` vs `Vector` change

**Comment by manishbansal8843** [comment]
@SethTisue Changed `++:` back to `++`

**Comment by som-snytt** [comment]
Apparently, it is confusing, indeed. The comment that the doc was prepending is wrong. There is a paragraph about appending, followed by another about prepending.

What's the difference between `concat` and `appendedAll` again? There is probably not a simple way to make it unconfusing.

I'd suggest squashing away the confused commit.

**Comment by martijnhoekstra** [comment]
I understand the motivation to write `prefix ++: a`, as `++:` is the operation that prepends to `a`. Conceptually, `prefix ++ a` is something different from `prefix ++: a`. That becomes more apparent if `prefix: List[Int]` instead of `prefix: Vector[Int]`: `prefix ++ a` then has a different outcome than `prefix ++: a`

But I really don't know whether or not that's better in the context of teaching materials and contrasting prepending and appending.

Anyway, the PR as it stands now is definitely an improvement to the previous situation, regardless of whether the bikeshed is appended to the building, or the building prepended to the bikeshed.

**Comment by SethTisue** [comment]
thank you @manishbansal8843

**Pull request merged**
