### PR TITLE
Update quotes.md

### PR DESCRIPTION
**Pull request by toddobryan**
I think the first two things are just typos. The third seems much easier for me, as a native English speaker, to understand.

### CODE REVIEW

**Review by julienrf — APPROVED** [review]
Thank you @toddobryan ! I agree with your analysis. Can @nicolasstucki confirm?

**Review by nicolasstucki — APPROVED** [review]

**Comment by nicolasstucki** [comment]
@toddobryan was a conflict with another PR. Could you rebase?

**Comment by julienrf** [comment]
@toddobryan Could you please fix the Git conflict?

**Comment by toddobryan** [comment]
Sorry that took so long. While I was at it, I tried to clarify it a little bit more, but may have made it worse.

**Comment by julienrf** [comment]
Thank you!

**Pull request merged**
