### PR TITLE
Fix the Docker setup

### PR DESCRIPTION
**Pull request by julienrf**
I found that our previous Docker setup was not good enough and was failing on some machines.

I propose the following changes, based on what has been done on the scala.epfl.ch website. The main “fix” is that we indicate a specific version of Ruby, rouge, and bundler. We also propose a different way to invoke docker-compose up that writes the generated files as a regular user (instead of root).

### CODE REVIEW

**Review by SethTisue — APPROVED** [review]
do you see "Docker guy" on my LinkedIn profile?!?!?!?! :-P

before this PR, on my Mac I got:

```
#0 103.4 ERROR:  Error installing jekyll:
#0 103.4 	The last version of rouge (>= 3.0, < 5.0) to support your Ruby & RubyGems was 3.30.0. Try installing it with `gem install rouge -v 3.30.0` and then running the current command again
#0 103.4 	rouge requires Ruby version >= 2.7. The current ruby version is 2.6.10.210.
```

and after this PR it worked

so I'd say that's an "Approve", even though I have no idea what any of this is about

as I also said at https://github.com/scala/docs.scala-lang/issues/1286,

> how do I view the site? (visiting http://0.0.0.0:4000/ doesn't work

I guess because the site is running inside the container and my web browser is outside of the container? So this is "working" in the sense that site seems to build, but without understanding how to actually view the site, all the Docker stuff still isn't actually helping me.

**Comment by julienrf** [comment]
I guess you don't see the website because of VirtualBox.

**Comment by SethTisue** [comment]
I did switch from using VirtualBox to using the Docker desktop app.

It appears from https://www.mend.io/free-developer-tools/blog/docker-expose-port/ that we should be able to add something to the Dockerfile that exposes port 4000. I might mess with that if I get a chance. (I joke about not wanting to mess with Docker, but it’s also been frustrating messing with rbenv and bundler and such over the years, so I actually am interested in improving the Docker option.)

**Comment by fsalvi** [comment]
Port 4000 is already exposed, it works fine under linux. I guess it's a bit different on mac...

**Review by fsalvi — APPROVED** [review]
Works fine under linux

**Pull request merged**
