### PR TITLE
style: Improve UX for users with large screens #2028

### PR DESCRIPTION
**Pull request by fernandoracca**
Expand the main content area to fill up all available space.

### CODE REVIEW

**Comment by b-studios** [comment]
Also, it would be important to make the same change over at https://github.com/scala/scala-lang

**Comment by b-studios** [comment]
Just for comparison: 

docs now

image

docs with 1280px

image

landing page with 1280px

image

scala home with 1280px

**Comment by b-studios** [comment]
LGTM, @SethTisue or @julienrf could we have a second pair of eyes?

**Review by b-studios — APPROVED** [review]

**Review by julienrf — APPROVED** [review]

**Comment by julienrf** [comment]
I personally don’t like when rows are too wide but 1280px seems OK to me. Maybe an alternative solution to take advantage of large screens would be to show sidebars with additional information (although we already have some sidebars on some pages) rather than increasing the width of the main content? Anyway, that could be worked on a separate PR, I think this PR finds a good compromise.

**Comment by b-studios** [comment]
@fernandoracca could you maybe open a PR with the same change at https://github.com/scala/scala-lang ? This way we make sure the two pages are consistent.

**Pull request merged**
