### PR TITLE
copyedit new package object tour section

### PR DESCRIPTION
**Pull request by SethTisue**
(followup to https://github.com/scala/docs.scala-lang/pull/1203)

### CODE REVIEW

**Comment by SethTisue** [comment]
review by @zafarella ? (and/or by anyone watching the repo)

**Comment by SethTisue** [comment]
> lgtm. I think type annotation is not really required though

true in Scala 2.12, but procedure syntax will be deprecated in Scala 2.13 and removed in some version after that. 2.13 warns: "warning: procedure syntax is deprecated: instead, add `: Unit =` to explicitly declare `foo`'s return type"

so we want to steer people away from it starting now.

**Comment by SethTisue** [comment]
geez GitHub, do you have to show how the world how many force-pushes it's taking me to get this right? 🤨

**Comment by Philippus** [comment]
Maybe it would be good to add a note to discourage defining classes/objects inside of package objects. (which will result in warnings when using `-Xlint`)

**Pull request merged**
