### PR TITLE
reorganize Overviews page

### PR DESCRIPTION
**Pull request by SethTisue**
* split "Core Scala" into "Language" and "Standard Library"
* make a new "Compatibility" section
* remove obsolete actors guides

### CODE REVIEW

**Comment by SethTisue** [comment]
the main thing I wanted to do here was collect the three compatibility guides into their own section.

**Comment by SethTisue** [comment]
now live at http://docs.scala-lang.org/overviews/index.html

**Comment by heathermiller** [comment]
I wouldn't delete the old Scala Actors guide. People are still using it, as far as I've heard... Maybe it makes more sense to put this in another category, like "Legacy" or something?

**Comment by heathermiller** [comment]
Otherwise, it looks good!

One minor nitpick–would it make sense to shuffle the order of the sections? E.g., to have the standard library section come first? And the language section to come afterwards? I'd expect more people are interested in the collections guide than the value classes and universal traits docs, which come first on the page.

**Comment by SethTisue** [comment]
> Maybe it makes more sense to put this in another category, like "Legacy" or something?

note that I didn't delete the guides, just the links. but yeah, on second thought actually I think you're right, a legacy section is a good idea.

> have the standard library section come first

good idea

I'll make a new PR with these two changes.

**Comment by heathermiller** [comment]
❤️

**Pull request merged**
