### PR TITLE
Update migration guide

### PR DESCRIPTION
**Pull request by adpi2**
- Updated to latest versions of Scala (3.3.1, 2.13.11)
- `sbt-scala3-migrate` tutorial moved to tutorials chapter
- `sbt-scala3-migrate` tutorial rewritten using version 0.6.1

Screenshot 2023-09-08 at 09-54-16 Porting an sbt Project (using sbt-scala3-migrate)

### CODE REVIEW

**Comment by sjrd** [comment]
FYI: there's also Scala 2.13.12 since yesterday.

**Comment by adpi2** [comment]
> FYI: there's also Scala 2.13.12 since yesterday.

It seems it is not announced yet. But I would like to merge this PR asap. @sjrd can you review it quickly?

**Comment by sjrd** [comment]
Perhaps tonight. Until then I'll be busy away from a computer.

**Comment by sjrd** [comment]
I've been not well all day. I won't be able to have a look at it tonight.

**Comment by adpi2** [comment]
I am merging it, but I hope you can take a look at it later.

**Pull request merged**
