### PR TITLE
Attempt to fix the rendering issues

### PR DESCRIPTION
**Pull request by robstoll**
Not entirely sure if this will help but many times a missing line in conjunction with `<details>` was the problem

### CODE REVIEW

**Comment by julienrf** [comment]
@robstoll may ask you to provide a screenshot of before and after your PR?

**Comment by robstoll** [comment]
I have not checked out the project, I only did it via the web gui of github. Feel free to close the PR. This is a try and error approach.

**Comment by SethTisue** [comment]
Anyone want to adopt this PR and see if it should be merged?

**Comment by Philippus** [comment]
I tried it out, but it doesn't solve the issue. It looks like using ````scala ` inside a summary tag is not possible. Maybe there's some jekyll-magic that can solve this, or we can choose not to use the summary tag. We don't use it anywhere else in the documentation.

**Comment by robstoll** [comment]
@Philippus thanks for taking the time to try it out :+1:

**Pull request closed without merging**
