### PR TITLE
Fix syntax error on Scala 3.3.1

### PR DESCRIPTION
**Pull request by Dieken**

### CODE REVIEW

**Review by Philippus — APPROVED** [review]

**Comment by Philippus** [comment]
Maybe also changed it here in one go: https://github.com/scala/docs.scala-lang/blob/68e3b5ce9fe30c43a7249f4d3675ffd441cefab2/_zh-cn/overviews/scala3-book/scala-for-java-devs.md?plain=1#L490

**Comment by Dieken** [comment]
Pushed again, thanks for your reminder!

**Review by bishabosha — COMMENTED** [review]
this is valid syntax in Scala 3

**Comment by Philippus** [comment]
I get:

```
Welcome to Scala 3.3.1 (17.0.10, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.
>....                                                                                                                                                                       | 
     | trait Green:
     |   println("I’m green")
     | 
     | // mix in the traits as DavidBanner
     | // is created
     | val hulk = new DavidBanner with Big, Angry, Green
-- Error: ----------------------------------------------------------------------
15 |val hulk = new DavidBanner with Big, Angry, Green
   |                                   ^
   |                                 end of statement expected but ',' found
```

**Comment by bishabosha** [comment]
oh right, sorry about that I didn't notice it was an anonymous class instance!

**Review by bishabosha — APPROVED** [review]

**Pull request merged**
