### PR TITLE
Update higher-order-functions.md

### PR DESCRIPTION
**Pull request by verkhovin**
I believe "http" should be returned in case when `ssl` is `false` :)

### CODE REVIEW

**Comment by Philippus** [comment]
Good catch! Would you mind making this change in the translated tours as well?

**Comment by verkhovin** [comment]
oh, sure. I'll run through the translations and make changes there too.

**Comment by verkhovin** [comment]
@Philippus done.

**Comment by Philippus** [comment]
Thank you!

**Pull request merged**
