### PR TITLE
Update the collection guide for 2.13

### LINKED ISSUE #995: Update the collections guide to the new collections framework
http://docs.scala-lang.org/overviews/collections/introduction.html

Most of the content should be still valid. Here are the actions needed:
- make a new guide for 2.13 so that it coexists with the current guide (maybe not! we should first try to keep a single guide with version-specific sections when necessary),
- remove the “Traversable” page and merge it with the “Iterable” page,
- remove the “migrating from 2.7” page (only if we do two guides),
- add a page about non-strict collections: views, lazy list, iterators.

### PR DESCRIPTION
**Pull request by julienrf**
Fixes #995

I’ve split the PR into two commits for easier review. The first commit duplicates the current collection guide into a “Scala 2.13” guide, without changing its contents. The second commit applies the necessary changes. As a result, you can review just the second commit to see the differences with the current collections guide.

Here are some screenshots of the layout and diagrams.

index
overview-root
overview-immutable
overview-mutable

### CODE REVIEW

**Comment by SethTisue** [comment]
> Could you review, please, @szeiger?

(we need to finish 2.13.0-RC1 first, then we'll give higher priority to doc work)

**Comment by SethTisue** [comment]
note to self, I should go ahead and give this a light round of review and then merge it. if it needs more work we can always improve it further later

**Comment by SethTisue** [comment]
@julienrf would you mind fixing this up before merge?

```
- ./_site/overviews/collections-2.13/concrete-immutable-collection-classes.html
  *  External link http://www.scala-lang.org/api/2.12.2/scala/collection/immutable/ArraySeq.html failed: 404 No error
  *  External link http://www.scala-lang.org/api/2.12.2/scala/collection/immutable/LazyList.html failed: 404 No error
  *  External link http://www.scala-lang.org/api/2.12.2/scala/collection/immutable/VectorMap.html failed: 404 No error
- ./_site/overviews/collections-2.13/concrete-mutable-collection-classes.html
  *  External link http://www.scala-lang.org/api/2.12.2/scala/collection/mutable/ArrayDeque.html failed: 892
- ./_site/overviews/collections-2.13/iterators.html
  *  External link http://www.scala-lang.org/api/2.12.2/scala/collection/IterableOnce.html failed: 404 No error
- ./_site/overviews/collections-2.13/overview.html
  *  External link http://www.scala-lang.org/api/current/scala/collection/immutable/LazyList.html failed: - ./_site/overviews/collections-2.13/trait-iterable.html
  *  External link http://www.scala-lang.org/api/current/scala/collection/IterableOnce.html failed: 404 No error
  *  External link https://www.scala-lang.org/api/current/scala/collection/SetOps.html failed: 404 No error
- ./_site/sips/minutes/2018-09-24-sip-minutes.html
  *  External link https://dotty.epfl.ch/docs/reference/dependent-function-types.html failed: 404 No error
  *  External link https://dotty.epfl.ch/docs/reference/implicit-function-types.html failed: 404 No error
  *  External link https://dotty.epfl.ch/docs/reference/intersection-types.html failed: 404 No error
  *  External link https://dotty.epfl.ch/docs/reference/trait-parameters.html failed: 404 No error
  *  External link https://dotty.epfl.ch/docs/reference/union-types.html failed: 404 No error
- ./_site/tutorials/scala-with-maven.html
  *  External link http://maven.apache.org/plugins/maven-assembly-plugin/project-summary.html failed: 404 No error
```

**Comment by julienrf** [comment]
These links are computed by using the `site.scala-version` variable, which happens to be [set to `2.12.2`](https://github.com/scala/docs.scala-lang/blob/a276a2940f17f5208f0b69ed4f35e84b7d713eec/_config.yml#L18). Should I hardcode them to use `2.13.0-M5` instead?

**Comment by SethTisue** [comment]
hardcoding would be fine. if you're feeling a little more ambitious, you could add a `site.scala-213-version` variable

I'll submit a separate PR bumping `site.scala-version`, and I'll add updating that to our release steps for Scala

**Comment by julienrf** [comment]
I felt ambitious.

**Pull request merged**
