### PR TITLE
Add consistency to parameter lists formatting

### PR DESCRIPTION
**Pull request by arbitrary-dev**
To make it more in line with argument list formatting of #classes

### CODE REVIEW

**Comment by SethTisue** [comment]
can't say I've seen this style around much. is there any evidence there's consensus on this? does scalafmt do it this way?

**Comment by arbitrary-dev** [comment]
>is there any evidence there's consensus on this?

Not that I'm aware of.

To my opinion, [parameter lists for method](https://docs.scala-lang.org/style/declarations.html#multiple-parameter-lists) should be formatted the same as for [classes](https://docs.scala-lang.org/style/declarations.html#classes), but currently they are different, which is confusing.

>does scalafmt do it this way?

Here's default formatting with scalafmt 2.7.5:
```
sbt:scalafmtRoot> tests/testOnly *FormatTests -- -z "Test default param list formatting"
[info] Compiling 1 Scala source to /home/man/work/scalafmt/scalafmt-dynamic/target/scala-2.13/classes ...
[info] Compiling 2 Scala sources to /home/man/work/scalafmt/scalafmt-core/jvm/target/scala-2.13/classes ...
FormatTests:92 Total explored: 316
[info] FormatTests:
[info] - default/DefDef.stat:327: Test default param list formatting           | *** FAILED ***
[info]   ===========
[info]   => Obtained
[info]   ===========
[info]   protected def forResource(resourceInfo: Any)(f: (JsonNode) => Any)(implicit
[info]       urlCreator: URLCreator,
[info]       configurer: OAuthConfiguration): Any = {
[info]     ???
[info]   }
[info]   
[info]            
[info]   =======
[info]   => Diff
[info]   =======
[info]   -protected def forResource(resourceInfo: Any)
[info]   -                         (f: (JsonNode) => Any)
[info]   -                         (implicit urlCreator: URLCreator, configurer: OAuthConfiguration): Any = {
[info]   +protected def forResource(resourceInfo: Any)(f: (JsonNode) => Any)(implicit
[info]   +    urlCreator: URLCreator,
[info]   +    configurer: OAuthConfiguration): Any = {
[info]      ??? (DefDef.stat:327)
```

Also long parameter lists hanging to the right are difficult to read on small screens, vertical scrolling is often required.

**Comment by SethTisue** [comment]
The style guide doesn't aim to resolve all style questions, only questions on which consensus or near-consensus exists.

So I think we could accept this PR if it were modified to offer alternatives, but I don't think it's mergeable to enshrine the style you are recommending here as _the_ style.

**Comment by SethTisue** [comment]
closing for inactivity. happy to reopen if activity resumes

**Pull request closed without merging**
