### PR TITLE
Add Scala 2.12.7

### PR DESCRIPTION
**Pull request by Philippus**

### CODE REVIEW

**Comment by SethTisue** [comment]
@jvican Drone is stuck, can you kick it?

**Comment by jvican** [comment]
Done, thanks for the ping. I restarted the servers so it's likely that the GH hook didn't see the failure of the CI run.

**Comment by smarter** [comment]
@SethTisue Maybe updating this documentation page should be added to the [release checklist](https://github.com/scala/scala-dev/blob/scala-dev/notes/releases/template.md) ?

**Comment by Philippus** [comment]
sorry to bother you @SethTisue , but let's merge this :)

**Comment by SethTisue** [comment]
> Maybe updating this documentation page should be added to the release checklist ?

done, https://github.com/scala/scala-dev/commit/b11cd2e4a4431de7867db6b39362bea8fa6650e7

**Pull request merged**
