### PR TITLE
Fix: Prevent the code text from sticking out of the div in Settings page documentation

### PR DESCRIPTION
**Pull request by Dedelweiss**
On the settings page, the code for the -social-links flag is sticking out.
On this PR, I just added a overflow scroll to the p elements with code.
Before:
Screenshot 2023-03-01 at 16 11 04

After:
Screenshot 2023-03-02 at 16 24 15

Reviewed-by: @ckipp01

### CODE REVIEW

**Review by ckipp01 — COMMENTED** [review]
Thanks for the pr @Dedelweiss! Since this is code, do you think instead of breaking we may just want instead have an overflow that you can scroll left and right with? I typically don't like that, but in this case it might make the most sense since you don't want to potentially break on code in a place that's showing actual code, causing confusion. Wdyt?

**Comment by ckipp01** [comment]
I think my personal preference is your first one with the overflow on the single line. It _may_ not be super obvious, but at the same time it doesn't break the screen and provides the ability to work.

**Comment by Dedelweiss** [comment]
Desc updated

**Review by ckipp01 — APPROVED** [review]
Great, thanks @Dedelweiss!

**Comment by julienrf** [comment]
On Chrome the result does not look good:

Screenshot from 2023-03-13 15-12-09

**Comment by julienrf** [comment]
It seems `overflow: auto` is a better fit because the scrollbars are shown only if the content does not fit:

Screenshot from 2023-03-13 15-17-36

**Comment by julienrf** [comment]
Actually on Firefox I see no scrollbars :thinking: 

Screenshot from 2023-03-13 15-19-58

**Comment by julienrf** [comment]
I’ve reverted the PR for now. I am not sure what should be the correct solution.

**Comment by Dedelweiss** [comment]
Okay sorry, I will see for a better solution.

**Comment by julienrf** [comment]
No problem, thank you for your help! Getting something that works consistently across browsers is not that easy…

**Pull request merged**
