### PR TITLE
Add a missing translation in getting-started.md (Japanese)

### PR DESCRIPTION
**Pull request by komainu8**

### CODE REVIEW

**Comment by SethTisue** [comment]
review by @scala/docs-ja? (not sure why GitHub won't let me use the "request reviewers" feature to do this...)

**Review by eed3si9n — APPROVED** [review]
Thanks!

**Comment by eed3si9n** [comment]
@SethTisue 

> (not sure why GitHub won't let me use the "request reviewers" feature to do this...)

I think docs-zh team has push rights on the repo, but other language teams do not?

**Comment by SethTisue** [comment]
thank you @komainu8 and @eed3si9n !

**Pull request merged**
