### PR TITLE
Adds the DevInsideYou YouTube channel

### PR DESCRIPTION
**Pull request by agilesteel**

### CODE REVIEW

**Review by propensive — APPROVED** [review]

**Comment by leobenkel** [comment]
This should be approved ! This channel is amazing ! Learned so much from it! I recommend. Too bad I don't have permission to merge ! Haha

**Review by leobenkel — APPROVED** [review]

**Review by softinio — APPROVED** [review]
LGTM

**Comment by SethTisue** [comment]
we prefer not to include subjective descriptions like "high quality" that resemble advertising copy. can you make more neutral/objective?

**Comment by agilesteel** [comment]
@SethTisue sure thing, done.

**Comment by agilesteel** [comment]
@SethTisue is it good like this?

**Pull request merged**
