### PR TITLE
Add a command execution result

### PR DESCRIPTION
**Pull request by komainu8**
Dear, developers.

We added a command execution result.
Because in my opinion easier to understand to output a result.

### CODE REVIEW

**Comment by exoego** [comment]
Since this is language-agnostic, could you consider apply this changes to all translations ?

**Comment by komainu8** [comment]
Does all translations means Japanese and simplified Chinese?

**Comment by komainu8** [comment]
I applied this change to Japanese and simplified Chinese.

**Comment by SethTisue** [comment]
there's others:

```
% git grep getSquareString
_ba/tour/basics.md:def getSquareString(input: Double): String = {
_es/tour/basics.md:def getSquareString(input: Double): String = {
_ja/tour/basics.md:def getSquareString(input: Double): String = {
_ko/tour/basics.md:def getSquareString(input: Double): String = {
_pl/tour/basics.md:def getSquareString(input: Double): String = {
_ru/tour/basics.md:def getSquareString(input: Double): String = {
_th/tour/basics.md:def getSquareString(input: Double): String = {
_tour/basics.md:def getSquareString(input: Double): String = {
_zh-cn/tour/basics.md:def getSquareString(input: Double): String = {
```

**Comment by komainu8** [comment]
@SethTisue
Thank you very much!
I'll also modify remaining languages.

**Comment by komainu8** [comment]
Thank you for your comments.
I've fixed them.

**Comment by SethTisue** [comment]
thank you!

**Pull request merged**
