### PR TITLE
remove dead links

### PR DESCRIPTION
**Pull request by SethTisue**
this came up in a CI run for an unrelated PR, see
https://platform-ci.scala-lang.org/scala/docs.scala-lang/374

### CODE REVIEW

**Comment by SethTisue** [comment]
so far so good on the Java 5 links, but there's still a link being reported as broken:

```
- ./_site/getting-started-intellij-track/getting-started-with-scala-in-intellij.html
  *  External link http://www.oracle.com/technetwork/java/javase/downloads/index.html failed: 401 No error
```

but when I `curl` that URL, I get 200, not 401. anyone know what could be causing this or what we should do about it...?

**Comment by heathermiller** [comment]
Looks like ignoring the 401 code would fix it:
https://github.com/gjtorikian/html-proofer/issues/336#issuecomment-284109325

**Comment by heathermiller** [comment]
This should work:
https://github.com/scala/docs.scala-lang/commit/202dbdea08110e9de7725fe2b66ed0423a98adf8

(Don't have push rights to SethTisue/docs.scala-lang, otherwise I'd add it to this PR)

**Comment by SethTisue** [comment]
thanks Heather

**Pull request merged**
