### PR TITLE
Updated Thai translation

### PR DESCRIPTION
**Pull request by iphayao**
#Hacktoberfest

### CODE REVIEW

**Comment by SethTisue** [comment]
Can you suggest another Thai speaker to review the translation...?

**Comment by SethTisue** [comment]
I put a call for reviewers at https://contributors.scala-lang.org/t/speak-chinese-thai-or-korean-pr-review-needed/2442

**Comment by ooHAoo** [comment]
Hi,
I speak Thai and I'm going to review the translation.
Thanks

**Comment by SethTisue** [comment]
since no reviewers have appeared, optimistically merging. thank you!

**Pull request merged**
