### PR TITLE
Add Thai translation

### PR DESCRIPTION
**Pull request by iphayao**
Adding Thai translation, start with cheatsheets

### CODE REVIEW

**Comment by xingyif** [comment]
@SethTisue said:

"ultimately we'll end up merging it regardless, but we do normally prefer to have two sets of native-speaker eyes on translations if we can get them"

**Comment by iphayao** [comment]
I don't have other to work with me for this translation, it's no chance to merge.

**Comment by Philippus** [comment]
let's wait a while, there's a lot of users on GitHub. Hopefully somebody steps up to validate the PR.

**Comment by kajornsakp** [comment]
This translation seems to be a little bit rough for me (as a native speaker). In my opinion, some specific words should not be translated into Thai (since those words are not exists in Thai dictionary). So, It might be easier for the reader if you can keep those words in English.

Also, the structure of each sentence should be adapt into Thai sentence's structure. This translation seems to be reversed.

And some typos like อ้างอิ่ง -> อ้างอิง, ตัวแปล -> ตัวแปร

**Comment by iphayao** [comment]
@kajornsakp Thank you for reviewed, I will fixed as your mentions.

What we should do on translation between transliteration and keep it in English.

**Comment by jvican** [comment]
@iphayao Could you rebase this on top of master and let me know when this is good to be merged? :smile:

**Comment by iphayao** [comment]
@jvican I did rebased from master, please go ahead to merge for Thai translation initial.

Thank you ^_^

**Comment by SethTisue** [comment]
thanks all!

**Pull request merged**
