### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by asakaev**

### CODE REVIEW

**Comment by SethTisue** [comment]
LGTM except possibly for the apostrophe change. in typography, it's standard practice to prefer a "curly" apostrophe and never use the "straight" one (see e.g. https://typographyforlawyers.com/straight-and-curly-quotes.html), so that part seems like a step backwards to me.

**Comment by dwijnand** [comment]
Similarly, the change from em-dash to hyphen-minus is a regression in my eyes.

**Comment by asakaev** [comment]
@SethTisue Thanks for the English typography. I did not know about apostrophes, a very interesting book.
@dwijnand It was not hyphen-minus but em-dash symbol, but I will do it in the next PR.

**Comment by ashawley** [comment]
Looking at the HTML output from Jekyll, it seems it gets the typography folks desire here when you use the ASCII straight apostrophe, double quotes, or double hyphens for em dash.

**Pull request merged**
