### PR TITLE
Update scala-with-maven.md

### PR DESCRIPTION
**Pull request by ekrich**
Author change - guessing.

### CODE REVIEW

**Comment by SethTisue** [comment]
lol, @adriaanm this isn't by you, or is it? who is the mysterious "Adrian Null", anyway? @heathermiller you remember anything about this?

**Comment by adriaanm** [comment]
Haha, I have no recollection of writing this tutorial. I think. Pretty sure that’s not me.

**Comment by ekrich** [comment]
Sure you can claim him if you like - I was just trying to make a contribution - sorry it was a joke.

**Comment by Raekye** [comment]
@SethTisue Hi, that is me / my pseudonym, I added it because the other tutorials at the time had an author. It can be changed to something more appropriate if necessary. Thanks for checking!

**Comment by ekrich** [comment]
@SethTisue @Raekye Thanks for looking into this - the name just seemed a little funny - maybe these without authors attributed would be better to get outside contributions, updates.

**Comment by SethTisue** [comment]
> Also, I had updated the guide some time ago, but it may need updating again... I can do it if necessary

@Raekye that would be exceedingly welcome

> maybe these without authors attributed would be better to get outside contributions, updates

@ekrich yeah, there's a tension here between wanting to credit authors, and wanting to encourage collective ownership

**Pull request closed without merging**
