### PR TITLE
Add types-intersection.md and types-union.md in ru

### PR DESCRIPTION
**Pull request by artemkorsakov**
Add types-intersection.md and types-union.md in russian

### CODE REVIEW

**Comment by artemkorsakov** [comment]
@kotobotov @DespiteDeath could you please review this PR?

**Review by kotobotov — APPROVED** [review]
LGTM

**Comment by artemkorsakov** [comment]
@sjrd @julienrf Could you please merge this approved PR?

**Comment by julienrf** [comment]
Thank you!

**Pull request merged**
