### PR TITLE
Added Scroll to top button.

### PR DESCRIPTION
**Pull request by pckrishnadas88**
Added a scroll to top button. It may be helpful for the users as some of the pages contains long scrolls. A screen shot of the same from my local environment is also attached.
scroll-to-top

### CODE REVIEW

**Comment by pckrishnadas88** [comment]
@SethTisue . Is this change useful or do I need to remove it from my fork as well?

**Comment by SethTisue** [comment]
it looks useful to me. I was hoping an external reviewer would weigh in

**Comment by pckrishnadas88** [comment]
Thank you for the feedback. Wish to serve the community more with the best of my knowledge.

**Comment by heathermiller** [comment]
Looks great to me! I guess I'll be the other external reviewer hehe. Thanks a lot doing this! It's great!

**Comment by pckrishnadas88** [comment]
@heathermiller Thank you for your kind words. Have a great day 👍

**Pull request merged**
