### PR TITLE
[FIX] Added empty pages of French to solve CI error

### PR DESCRIPTION
**Pull request by CastaChick**
#1820

### CODE REVIEW

**Comment by CastaChick** [comment]
Why doesn't the build start for a long time?

**Comment by SethTisue** [comment]
@sjrd can you or whoever the current Drone-meister is give Drone a kick?

**Comment by sjrd** [comment]
Pinging @fsalvi. It seems Drone is behaving weirdly.

**Comment by fsalvi** [comment]
Hello, I had problems to try to reactivate this build in drone. So I manually removed it. Could you submit it again ?

**Comment by sjrd** [comment]
@CastaChick Can you amend your commit without changes (`$ git commit --amend`) and force-push again to your branch, to convince the CI that there is a new commit that needs testing?

Sorry for the technical bump.

**Comment by CastaChick** [comment]
Thank you for your support 😄

**Comment by CastaChick** [comment]
Two errors have occurred. I'm going to fix it.

**Comment by CastaChick** [comment]
All errors are solved.
Could you check my changes?

**Comment by SethTisue** [comment]
excellent, thank you!!

**Pull request merged**
