### PR TITLE
Refresh multiple-parameter-lists.md in russian

### PR DESCRIPTION
**Pull request by artemkorsakov**
Refresh multiple-parameter-lists.md in russian

### CODE REVIEW

**Comment by artemkorsakov** [comment]
@kotobotov @DespiteDeath could you please review this PR?

**Review by kotobotov — APPROVED** [review]
LGTM

**Comment by artemkorsakov** [comment]
@sjrd @julienrf Could you please merge this approved PR?

**Comment by julienrf** [comment]
Thank you!

**Pull request merged**
