### PR TITLE
Add scroll to active toc

### PR DESCRIPTION
**Pull request by IZUMIRU**
If the toc is long, you may not know where you are reading when you read the chapter below.

I think there is a matter of preference regarding UX, so I will leave it to you to decide whether to merge or close:)

- http://localhost:4000/tour/tour-of-scala.html
- http://localhost:4000/scala3/book/introduction.html

https://github.com/scala/docs.scala-lang/assets/11635641/ce8cd5ff-62da-4014-958c-ea47b04be72c

### CODE REVIEW

**Comment by bishabosha** [comment]
I think this is great - I was wondering if you might like to improve the sidebar in "book" views as well - see https://docs.scala-lang.org/scala3/book/packaging-imports.html

**Comment by IZUMIRU** [comment]
@bishabosha 
Thanks for the review. I tried to fix it.

**Review by adpi2 — APPROVED** [review]
Looks like a useful improvement to me.

**Comment by IZUMIRU** [comment]
@bishabosha @adpi2 
Thanks for the review!
I'd like to ask you to merge this approved PR.
Need to wait for other reviews?

**Comment by SethTisue** [comment]
Thank you!

**Pull request merged**
