### PR TITLE
It translations

### PR DESCRIPTION
**Pull request by IowU**
basics.md and tuples.md come from this [pull request](https://github.com/scala/docs.scala-lang/pull/1811).

### CODE REVIEW

**Comment by SethTisue** [comment]
mind rebasing? that'll pull in #1832 and #1834, so then we'll see whether the CI failure here has anything to do with your changes or not

**Comment by SethTisue** [comment]
@dwijnand where does this PR stand?

**Comment by SethTisue** [comment]
```
- ./_site/it/tour/annotations.html
379s
1257
  *  internally linking to /bait/tour/annotations.html, which does not exist (line 0)
379s
1258
     <a href="/bait/tour/annotations.html" class="lang">Bosanski</a>
379s
1259
  *  internally linking to /esit/tour/annotations.html, which does not exist (line 0)
379s
1260
     <a href="/esit/tour/annotations.html" class="lang">Español</a>
...
```

**Comment by SethTisue** [comment]
ping @dwijnand

**Comment by SethTisue** [comment]
@dwijnand is the CI failure real or spurious?

**Comment by dwijnand** [comment]
No idea.  Can't tell if it's a function of this PR not being merged or if it's flakiness or it could be something else.  Either way, it's exhausted my patience.

**Comment by dwijnand** [comment]
Oh, I've forced pushed here, but it's not my PR.

**Comment by gabro** [comment]
@SethTisue I'll ask around and post an update in case someone's interested!

**Pull request closed without merging**
