### PR TITLE
Updated page metadata to include in tour

### PR DESCRIPTION
**Pull request by bradfordlynch**
The Traits page wasn't being included in the tour TOC, but was being referenced by the tour pages before and after it, Classes and Class Composition with Mixins respectively. Updated the page metadata to include it in the tour, and fix the other tags.

### CODE REVIEW

**Comment by Philippus** [comment]
the same goes for the 'Abstract Types' and 'Self-type' pages. Maybe fix those in the same PR if you have time?

**Comment by bradfordlynch** [comment]
Thanks for spotting those as well. I've updated my PR to include those changes too.

**Comment by bradfordlynch** [comment]
@Philippus Is there anything else you need me to do to get this merged?

**Comment by Philippus** [comment]
Looks good to me! I don't have merge rights. Maybe @SethTisue can do the honours?
With the Scala Days conference happening right now it could take a little longer.

**Comment by SethTisue** [comment]
thank you, Bradford! very good catch

**Pull request merged**
