### PR TITLE
Add links to the Scala 3 Language Specification.

### PR DESCRIPTION
**Pull request by sjrd**
image
image

### CODE REVIEW

**Review by SethTisue — APPROVED** [review]
LGTM 🎉

attn @Kordyjan, note the version-numbered spec link — updating that should be added to the Scala 3 release steps, I think

**Comment by SethTisue** [comment]
@sjrd I hope you're planning on blogging about this? At any length you choose. I think at least a short blog post to crow about this is definitely merited, and if you were in the mood to make it longer, I imagine any additional material you added about what was involved would be of great interest to language mavens.

**Comment by sjrd** [comment]
Yes, that's a good point. I'll see what I can do tomorrow.

**Comment by SethTisue** [comment]
I'll record my other feedback from our conversation earlier, which is that ideally it should be clear in the spec itself what pieces are still missing. Up front, or in an appendix, either way.

**Comment by sjrd** [comment]
Given's and using's 😅 
Yes, I'll follow up on that in the dotty repo tomorrow as well, once https://github.com/lampepfl/dotty/pull/18526 is merged for automatic updates.

**Pull request merged**
