### PR TITLE
Use Em Dash Syntax in Scala 3 doc

### PR DESCRIPTION
**Pull request by adpi2**
Em Dash symbol is coded `---` in markdown and `&mdash` in html.

### Result in markdown
image

### Result in html
image

### CODE REVIEW

**Review by b-studios — APPROVED** [review]

**Review by julienrf — APPROVED** [review]
Thank you Adrien!

We could improve it even further by removing the spaces before and after the em dashes, would you like to do it?

https://www.scribbr.com/language-rules/dashes/#the-em-dash-marking-a-break-in-a-sentence

**Comment by b-studios** [comment]
Regarding removing spaces: I personally don't like the style of removed whitespace around dashes. But maybe it's just a matter of taste.

**Comment by adpi2** [comment]
I think you are right @julienrf . The correct typography for `em-dash` is without spaces.

**Review by julienrf — APPROVED** [review]
Great, thank you!

The changes look good but I don’t think this PR should contain this commit: https://github.com/scala/docs.scala-lang/pull/1864/commits/613a394e396921b459da0edbd92462cc5e9f484d

**Comment by adpi2** [comment]
Oups...

It should be better now :)

**Pull request merged**
