### PR TITLE
Add Hands-on Scala Programming to list of books

### PR DESCRIPTION
**Pull request by lihaoyi**
Tested manually using `docker-compose up`, looks good and links work:

Screenshot 2020-06-06 09 34 56

Sister PR to https://github.com/scala/scala-lang/pull/1140

### CODE REVIEW

**Comment by lihaoyi** [comment]
@sjrd the list of books on `scala-lang` seems to be vestigal; as far as I can tell, it's unreachable by any links from the front page. However, it is still indexed by google, and turns up as the second entry after the `docs.scala-lang` page when you search `scala book`. Maybe we can just permanent redirect the `scala-lang` page to the `docs.scala-lang` page, or vice versa?

**Comment by sjrd** [comment]
A permanent redirect sounds like a good idea.

**Comment by SethTisue** [comment]
> A permanent redirect sounds like a good idea.

PR: #1143

**Comment by SethTisue** [comment]
also, a followup PR with some further changes to the books page: https://github.com/scala/docs.scala-lang/pull/1706

**Pull request merged**
