### PR TITLE
Russian Collections introduction

### PR DESCRIPTION
**Pull request by kotobotov**
new try

### CODE REVIEW

**Comment by SethTisue** [comment]
can you suggest a Russian-speaking reviewer?

**Comment by kotobotov** [comment]
maybe @agilesteel can help, he also had really good course on youtube about [scala collections](https://www.youtube.com/channel/UCSBUwLT9zXhUalKfJrc2q2A)

**Comment by SethTisue** [comment]
before we merge, can you:

* squash the commits?
* verify whether the Gemfile.lock change is intentional?

**Comment by kotobotov** [comment]
sure

**Comment by SethTisue** [comment]
thank you!

**Pull request merged**
