### PR TITLE
Update string interpolation docs with further information on escaping special chars

### LINKED ISSUE #1314: Mention / Adding a section on escaping (double quotes, dollar sign, etc) in String Interporlation
First and foremost, thank you for this awesome project 😄 !
This [article](https://docs.scala-lang.org/overviews/core/string-interpolation.html) doesn't say much escaping special character with string interpolations. IMHO, it would be helpful to highlight this works for special characters such as `double quotes`, `dollar sign` etc
It might be worth as well mentioning string interpolation with triple quotes as well

### PR DESCRIPTION
**Pull request by chloecollins**
Resolves  #1314

Added ways in which Interpolation with double quotes can be achieved. Dollar signs are already documented.

Are there are further characters which would be necessary?

### CODE REVIEW

**Comment by martijnhoekstra** [comment]
Including this in this particular section on the interpolations is somewhat misleading, in that you *can't* use `\` to escape double quotes in interpolations.

**Comment by SethTisue** [comment]
@chloecollins thanks for tackling this — do you think your changes ought to be adjusted to reflect Martijn's feedback?

**Comment by chloecollins** [comment]
Thanks, @martijnhoekstra - I see that you are correct in pointing out that the backslash symbol cannot be used in this way. Reading your documentation at https://docs.scala-lang.org/sips/interpolation-quote-escape.html has clarified this for me. I have removed that section and now only refer to triple quotes as a solution.

**Comment by SethTisue** [comment]
@martijnhoekstra wdyt of the latest version?

**Comment by martijnhoekstra** [comment]
Looks like a net positive, and mergeable to me. Making it an s interpolation rather than a string literal would be better still.

**Comment by SethTisue** [comment]
thank you @chloecollins! welcome to the repo

**Pull request merged**
