### PR TITLE
Use a numbered recipe style

### PR DESCRIPTION
**Pull request by alvinj**
Updated the *Using sbt with ScalaTest* section to use a numbered recipe style. I think this might be a little easier to follow.

### CODE REVIEW

**Review by julienrf — APPROVED** [review]

**Comment by SethTisue** [comment]
There's now a merge conflict.

**Comment by julienrf** [comment]
@alvinj, would you have some time to rebase your work and resolve the conflict?

**Comment by alvinj** [comment]
Yes, @julienrf, I will look at it this weekend, or earlier if possible.

**Comment by alvinj** [comment]
I’m sorry I haven’t been able to look at this yet, but I should be able to get to it on Tuesday morning.

**Comment by alvinj** [comment]
Hi @julienrf. Based on all the comments and commits I see here now, it looks like there’s a good chance I didn’t do this rebase properly. I’ve never done one before, and I thought I was doing well until I saw the “You have unmerged paths” message. Assuming this is messed up, please feel free to delete this PR and I can open a new one. Thanks.

**Comment by julienrf** [comment]
Hi Alvin, indeed the diff and the number of commits look wrong. Maybe it’s simpler to restart from scratch? Sorry for the inconvenience…

**Comment by alvinj** [comment]
> Sorry for the inconvenience…

No problem. I read up about “rebase vs. merge”, and I thought the rebase was going well, but then it wasn’t. :)

But these are simple changes to make to the tools-sbt.md file, so I’ll do a new PR for that this afternoon.

**Pull request closed without merging**
