### PR TITLE
Add 2.13.0 to the JDK compatibility table

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by Philippus** [comment]
Probably the "JDK 11 compatibility notes" require an update as well.

**Comment by dwijnand** [comment]
I had a look at it but didn't see anything.  What did you have in mind?

**Comment by Philippus** [comment]
The "As of" part doesn't mention 2.13.0 which could be misinterpreted I think.

**Comment by dwijnand** [comment]
Done.

**Pull request merged**
