### PR TITLE
Update scala-for-java-programmers.md

### PR DESCRIPTION
**Pull request by Raysphere24**
Complex型の説明を「素数」から「複素数」に変更
デフォルト値の説明において、数値型の「0」を（他の型と同様にmonospaceの）`0` に変更

### CODE REVIEW

**Comment by SethTisue** [comment]
why closed? (sorry, sometimes we're slow with review in this repo)

**Comment by Raysphere24** [comment]
Didn't get any response for days, so I supposed it will be rejected or ignored.
And I made two independent changes, I thought which might be bad.
Actually translating "Complex" into "素数" is completely wrong (it means "prime number").
If it matters to you, I would make a separate request.

**Comment by SethTisue** [comment]
we have a Chinese reviewing team we can @-mention to try to attract review: hey @scala/docs-zh !

@liufengyun you've typically reviewed Chinese language PRs, are you still interested in doing that even after your change of employer? should we keep you in @scala/docs-zh ?

@jxnu-liguobin can I interest you in being added to @scala/docs-zh?

**Comment by Raysphere24** [comment]
Actually this issue is about the Japanese-language docs...

**Comment by jxnu-liguobin** [comment]
> we have a team of Chinese-language reviewers we can @-mention to try to attract review: hey @scala/docs-zh !
> 
> @liufengyun you've typically reviewed Chinese language PRs, are you still interested in doing that even after your change of employer? should we keep you in @scala/docs-zh ?
> 
> @jxnu-liguobin can I interest you in being added to @scala/docs-zh?

Yes, I'd love to be able to help

**Comment by jxnu-liguobin** [comment]
> Actually this issue is about the Japanese-language docs...

Yes, and It should have nothing to do with language. It's just a matter of translation. 素数 in Chinese are also called 质数

**Comment by SethTisue** [comment]
> Actually this issue is about the Japanese-language docs

🤭🤦 gah, sorry about that 

I'll notify the right reviewer squad, then: @scala/docs-ja

**Comment by xuwei-k** [comment]
🙇 

https://github.com/scala/docs.scala-lang/pull/2084

**Pull request closed without merging**
