### PR TITLE
Add Scala 2 version of case classes that can evolve

### PR DESCRIPTION
**Pull request by julienrf**
The same approach as with Scala 3 also works with Scala 2 if you add the `-Xsource:3` compiler option.

### CODE REVIEW

**Review by bishabosha — APPROVED** [review]

**Comment by sideeffffect** [comment]
Just to be clear, with `-Xsource:3` and case class constructor `private`, both `copy` and `apply` are private too?

**Comment by julienrf** [comment]
> Just to be clear, with `-Xsource:3` and case class constructor `private`, both `copy` (in class) and `apply` (in companion) are private too?

Yes.

**Comment by sideeffffect** [comment]
But to be super duper clear, that means that adding `-Xsource:3` is a breaking change (assuming the project in question is using case classes), right?

**Comment by julienrf** [comment]
Indeed.

**Pull request merged**
