### PR TITLE
Delete actors-migration-guide.md

### PR DESCRIPTION
**Pull request by Khalian**
Remove scala actors migration guide : https://github.com/scala/docs.scala-lang/issues/2542

### CODE REVIEW

**Comment by bishabosha** [comment]
This should also delete the various translation, and remove and links to this page, e.g. from the index pages

**Comment by Khalian** [comment]
> This should also delete the various translation, and remove and links to this page, e.g. from the index pages

Yea I know. I will work on it shortly.

**Review by bishabosha — CHANGES_REQUESTED** [review]
you also need to delete `_zh-cn/overviews/core/actors-migration-guide.md`, and any links to that (tho I think you have)

**Comment by bishabosha** [comment]
> My apologies. This is my first time working on this repo and I did not know where all its present at first.

Its ok :) I'm sorry if I was too direct

**Comment by Khalian** [comment]
Yea I think I got rid of the links already. Now just deleted: _zh-cn/overviews/core/actors-migration-guide.md

I have a bunch of ruby gems to install on my mac and there are some issues so could not yet run bundle locally. 

It would be nice if the workflow was auto run instead of asking for a maintainer to run it. This way the CI/CD system would provide immediate feedback and the project maintainers can still enforce that only they can merge it pending a passed test and review.

**Comment by bishabosha** [comment]
> I have a bunch of ruby gems to install on my mac and there are some issues so could not yet run bundle locally.

you can try running with docker `docker-compose up` if you have that installed?

**Comment by Khalian** [comment]
Yea I do. I am gonna give it a try today. 

Btw the builds passed and the branch has no conflicts.

**Review by bishabosha — APPROVED** [review]
Thanks!

**Pull request merged**
