### PR TITLE
Update Gemfile.lock

### PR DESCRIPTION
**Pull request by byyue**
Probably related to macOS.

### CODE REVIEW

**Comment by julienrf** [comment]
Why is this change necessary?

**Comment by byyue** [comment]
It is imported automatically after installing dependencies on macOS. Otherwise, you may want to add this file into .gitignore.

**Comment by julienrf** [comment]
Does someone know what is the best practice regarding how to manage the Gemfile.lock?

**Comment by bishabosha** [comment]
I see this discussion suggesting the lock file should be committed as a "gem" for CI purposes, and then the one for your local machine you do not commit:
https://stackoverflow.com/a/4151540/2538602

**Review by SethTisue — APPROVED** [review]
none of us are really Gemfile jockeys afaik.

but, seeing as how it already has a similar entry for Linux and this seems to just do the same thing for MacOS, I can't see a reason not to merge this.

**Pull request merged**
