### PR TITLE
Implicits tour draft

### PR DESCRIPTION
**Pull request by siddhartha-gadgil**
I have attempted to address the reviewers comments, including

some rewriting,
a section on implicit classes,
new examples.
I have also added a section with a very basic case of typeclasses.

### CODE REVIEW

**Comment by SethTisue** [comment]
@siddhartha-gadgil glad you found your way to this repo. a lot has changed here since @travissarles did his work, the whole site was redone. it looks like you inadvertently pulled in some changes that are unrelated to your edits.

**Comment by SethTisue** [comment]
also you'll probably want to wait for #1018 to be merged. I think multiple people have been working on this part of the tour, and it seems certain now that #1018 will be merged first.

**Comment by SethTisue** [comment]
#1018 is merged now, but this might also overlap with #1003

**Comment by siddhartha-gadgil** [comment]
I'll redo what remains relevant.

Regards
Siddhartha

**Comment by siddhartha-gadgil** [comment]
Seems redundant given rewriting that is already merged.

**Comment by SethTisue** [comment]
sorry about what turned out to be redundant efforts — thanks for taking the time on it

**Pull request closed without merging**
