### PR TITLE
uu tube

### PR DESCRIPTION
**Pull request by som-snytt**
As in vacuum tube.

My French friend, who is a diacritical critic, says don't retain the accent in the short form:

> Séb: yeah, maybe

Maybe @sjrd will clarify for us barbarians.

### CODE REVIEW

**Comment by dwijnand** [comment]
Thanks!

**Comment by sjrd** [comment]
Indeed, in French the short form of Sébastien is Seb, without accent. This matches the prononciation, which becomes more Sèb than Séb. That change of prononciation has something to do with closed and open syllables, but I don't recall the precise rules right now.

**Comment by som-snytt** [comment]
Thanks. I asked my source of all things French to say the two phonemes, but I couldn't really distinguish them; or maybe my worsening tinnitus prevents me; but I still derive some pleasure from orthography.

**Comment by SethTisue** [comment]
> Indeed, in French the short form of Sébastien is Seb, without accent

I always wondered & now I know.

**Comment by som-snytt** [comment]
The other question is why Seb instead of Bas.

The great wonder is how Saint Seb survived the `=>`s.

**Pull request merged**
