### PR TITLE
Add info pointer for singleton and refinement types, #2933

### PR DESCRIPTION
**Pull request by vreuter**

### CODE REVIEW

**Comment by SethTisue** [comment]
We don't normally link from ordinary documentation — especially tutorial documentation like the Scala 3 Book — to the language specification, which is so much more formal and technical. We might link to the spec if no other reference documentation was available, but in this case, reference documentation is available and we already link to it.

(Does the reference documentation link to the relevant section of the spec? If not, it could and should.)

**Comment by SethTisue** [comment]
Oh, i see on the ticket that maybe @bishabosha doesn't agree. wdyt @bishabosha ?

**Comment by vreuter** [comment]
> Does the reference documentation link to the relevant section of the spec? If not, it could and should.)

Thanks for the context distinction b/w book and language spec and for suggesting the specific section links @SethTisue . I've added the more specific links here: https://github.com/scala/docs.scala-lang/pull/2934/commits/29c0b72dd852904e16df94fb9118f9e074e50626

**Comment by vreuter** [comment]
> Ideally I would suggest that you write a dedicated section, maybe you would like to come back and do that?

@bishabosha would you mean in the Book (e.g., https://docs.scala-lang.org/scala3/book/types-intersection.html) or in the Reference (e.g., https://docs.scala-lang.org/scala3/reference/new-types/intersection-types.html#)?

**Pull request merged**
