### PR TITLE
Fix links to mill and removed api doc

### PR DESCRIPTION
**Pull request by martijnhoekstra**
Fix a bunch of 404's

Ref #1953

### CODE REVIEW

**Comment by martijnhoekstra** [comment]
Remaining:

```
- ./_site/api/all.html
Ran on 985 files!
  *  External link https://www.scala-lang.org/files/archive/nightly/2.12.x/api/2.12.x/ failed: 404 No error

  *  External link https://www.scala-lang.org/files/archive/nightly/2.12.x/api/2.12.x/scala-compiler/ failed: 404 No error

  *  External link https://www.scala-lang.org/files/archive/nightly/2.13.x/api/2.13.x/scala-compiler/ failed: 404 No error
htmlproofer 3.15.3 | Error:  HTML-Proofer found 5 failures!
- ./_site/cheatsheets/index.html
  *  External link https://www.scala-lang.org/files/archive/nightly/2.13.x/api/2.13.x/ failed: 404 No error
```

Are they gone? Should they come back, or should the links also go?

**Comment by martijnhoekstra** [comment]
The lost nightlies are https://github.com/scala/scala-dev/issues/759

**Comment by martijnhoekstra** [comment]
I've just removed linking to the nightlies API doc. Getting things green here is the important bits. In the Glorious Future, when the nightlies are prim and proper again, we can link them again. Until that time of primality, maybe this will have to do.

**Comment by SethTisue** [comment]
excellent, much appreciated @martijnhoekstra !

**Pull request merged**
