### PR TITLE
Add Korean translation of tour

### PR DESCRIPTION
**Pull request by byeonggukgong**
* Update page numbers

* Translate basics.md in Korean

### CODE REVIEW

**Comment by byeonggukgong** [comment]
@heathermiller @sephlietz I would like to know the progress of this ticket review.

**Comment by byeonggukgong** [comment]
Thanks for answer!

I don't know official reviewer who can speak Korean. So that can a friend review the translations?

**Comment by SethTisue** [comment]
sure, a friend is fine

**Comment by alicek106** [comment]
Actually, translating English to another language directly is not desirable. @byeonggukgong translated document very well only for each noun or verb, but not the whole sentences. I recommend @byeonggukgong to refine sentence considering readability for Korean readers. 

For example, below sentence doesn't violate the original meaning of English sentence, but not naturally expressed in aspect of Korean context.

- 실행 버튼을 눌러라. 오른쪽 창에 출력이 나타난다.

can be modified like this.

- 실행 버튼을 누르면 오른쪽 창에서 출력 화면을 확인할 수 있다.

**Comment by jvican** [comment]
The CI is failing, it seems to be an error with the links. Could you have a look @byeonggukgong ?

**Comment by alicek106** [comment]
@byeonggukgong Translation is more naturally changed. I hope you to continue this works :D

**Comment by jvican** [comment]
Is this ready @byeonggukgong? Let's rebase this on top of master and we merge?

**Pull request merged**
