### PR TITLE
Fix: Increase the number of results of the doc search bar

### PR DESCRIPTION
**Pull request by Dedelweiss**
This PR corrects PR #2716 that I made.
In this one I set the search bar value of the blog to 5 as it was before and I set the search bar value of the documentation to 6 with distinct to true.
See the algolia documentation for:
- [hitsPerPage](https://www.algolia.com/doc/api-reference/api-parameters/hitsPerPage/)
- [distinct](https://www.algolia.com/doc/api-reference/api-parameters/distinct/?client=javascript)
### Before:
Screenshot 2023-03-07 at 10 02 42

### After:
Screenshot 2023-03-14 at 16 01 03

Also for the idea of having a paging system to be able to see other results. I've just seen that there is an open issue for this for DocSearch.
https://github.com/algolia/docsearch/issues/883

### CODE REVIEW

**Comment by ckipp01** [comment]
In your after image it shows two exact same `Scaladoc` results. Are those linking to the same page? Also is that the same page that is listed under Style Guide? Since we'd want to avoid multiple duplicates in the same result.

**Review by ckipp01 — APPROVED** [review]
Thanks for digging into this @Dedelweiss. This looks good to me.

LGTM

**Comment by SethTisue** [comment]
Thank you Lucas and Chris!

**Comment by Dedelweiss** [comment]
> Thank you Lucas and Chris!
Thanks to you. I'll keep in touch with the pagination issue created for [DocSearch](https://github.com/algolia/docsearch/issues/883) as it would indeed be interesting to implement it.

**Pull request merged**
