### PR TITLE
Polish version for-comprehensions

### PR DESCRIPTION
**Pull request by Filemon279**
Hello,
I have found that there was no polish version for for-comprehensions tour.
Hope you will enjoy it - I did.
Glad I can contribute to Scala.
Best regards, Filip.

### CODE REVIEW

**Comment by dwijnand** [comment]
@kamilduda any chance you'd be able to help collaborate with @Filemon279 here in landing this PR?  Thank you.

**Comment by kamilduda** [comment]
I personally wouldn't translate the code, I think it should remain in English - that way it's consistent with other pages of Polish version of tour @Filemon279 what do your think? 
Other than that it looks good 😃

**Comment by Filemon279** [comment]
@kamilduda You are right, It sure will be more consistent to keep examples in English language. I will do the changes :wink:

**Comment by Filemon279** [comment]
@kamilduda I've made the changes. Thanks you and @dwijnand for your help.

**Comment by kamilduda** [comment]
Oh there are still a couple of errors in code examples, you can check that particular build details here: https://ci.scala-lang.org/scala/docs.scala-lang/773/3 😉

**Comment by Filemon279** [comment]
@kamilduda My bad, fixed typo and It is building correctly now :wink:

**Comment by kamilduda** [comment]
@Filemon279 @dwijnand LGTM 😄

**Pull request merged**
