### PR TITLE
Add Korean translation for tuples

### PR DESCRIPTION
**Pull request by horace-velmont**
Hi. I translated the tuple part into Korean. I hope this helps.

### CODE REVIEW

**Comment by eed3si9n** [comment]
@horace-velmont Thanks for the contribution!

I can't review this myself, so could you find someone who can? /cc @yoohaemin, @hamelmoon, @byeonggukgong

**Comment by horace-velmont** [comment]
Oh.. it seems someone already translated this document #1403..  I did not see it by mistake. I'll close the request. Thanks.

**Comment by byeonggukgong** [comment]
@horace-velmont Then, how about reviewing #1403 together?

**Comment by horace-velmont** [comment]
@byeonggukgong Sure. I'll check about it!

**Pull request closed without merging**
