### PR TITLE
Fix links to sip-template.md

### PR DESCRIPTION
**Pull request by OlivierBlanvillain**

### CODE REVIEW

**Comment by jvican** [comment]
Merci @OlivierBlanvillain

**Comment by OlivierBlanvillain** [comment]
WDYT about adding [this line](https://github.com/scala/docs.scala-lang/blob/master/Gemfile#L3) to the CI?

**Comment by jvican** [comment]
Sounds good to me, but don't know why it hasn't been added!

**Comment by OlivierBlanvillain** [comment]
@jvican I did that in #947

**Pull request merged**
