### PR TITLE
Add consistency to parameter lists formatting

### PR DESCRIPTION
**Pull request by arbitrary-dev**
To make it consistent with argument list formatting of [Classes](https://docs.scala-lang.org/style/declarations.html#classes).

Previously: #1805

Alternative offered, please review once again @SethTisue

### CODE REVIEW

**Comment by SethTisue** [comment]
Is there evidence that this style is considered standard? Is it widely used?

**Comment by arbitrary-dev** [comment]
As I already mentioned in [this comment](https://github.com/scala/docs.scala-lang/pull/1952#issue-586265601), this change is only to bring consistency in the current scala docs, because in "Classes" this particular formatting is already used for long argument lists, but in this place formatting is different.

>Is there evidence that this style is considered standard?
Not that I know.

>Is it widely used?
I see more of these:
```
def method(with: Very, long: Long)(
  parameter: List[]): Unit = …
```

…rather than parentheses alignment, which I only observed in C world.

Also this one is from `scalatest`:
https://github.com/scalatest/scalatest/blob/3.2.x-new/jvm/core/src/main/scala/org/scalatest/Engine.scala#L125

Overall, I'm not insisting. Could be just a proposal, an alternative, I preserved parentheses alignment case in the docs.

Me personally find this one more pleasing than others and it also facilitates having cleaner git diffs in refactorings, when parameters are each on their own lines without any parentheses. Plus reading vertically is way easier than finding parameters in horizontal plane, especially for people using terminals with short width.

**Comment by arbitrary-dev** [comment]
Updated, please check.

**Comment by SethTisue** [comment]
thank you!

**Pull request merged**
