### PR TITLE
Add Korean translation of Packages and Imports in tour

### PR DESCRIPTION
**Pull request by byeonggukgong**
Translate Packages and Imports in tour :)

### CODE REVIEW

**Comment by byeonggukgong** [comment]
@alicek106 Can I asked you review? If you have some time :)

**Comment by SethTisue** [comment]
I also put a call for reviewers at https://contributors.scala-lang.org/t/speak-chinese-thai-or-korean-pr-review-needed/2442

**Comment by byeonggukgong** [comment]
@SethTisue @Naetmul Thanks for help and review, and I have a question to ask @Naetmul.

I have seen "트레이트" in the translation "Programming in Scala", why "Trait" should be translated into "트레잇"?  I'm so confused which expression is correct.

**Comment by Naetmul** [comment]
@byeonggukgong 
> I have seen the term "트레이트" in the Korean version of _Programming in Scala_, why should "Trait" be translated into "트레잇"? I'm so confused which term I should use.

Because [Tour/Traits](https://docs.scala-lang.org/ko/tour/traits.html) already used 트레잇.
그런데 외래어 표기법에 따르면 great와 마찬가지 발음이므로 '트레이트'라고 적는 게 맞습니다.
It may be better to change 트레잇 to 트레이트 in the linked page.
이미 트레이트로 번역한 책이 있다면 이 문서는 트레이트로 두죠.

**Comment by byeonggukgong** [comment]
@Naetmul

> It may be better to change 트레잇 to 트레이트 in the linked page.
이미 트레이트로 번역한 책이 있다면 이 문서는 트레이트로 두죠.
Tour/Basics에서는 또 트레이트라고 적혀 있고

Because I did the translation.

Anyway, I fixed the translation as you reviewed without changing "트레이트" to "트레잇". I would appreciate it if you could review it once more.

**Comment by byeonggukgong** [comment]
@SethTisue PR and review all done!

**Comment by SethTisue** [comment]
thank you!

**Pull request merged**
