### PR TITLE
Refine pattern-matching.md

### PR DESCRIPTION
**Pull request by asakaev**
number is a better name than many here.

### CODE REVIEW

**Comment by dwijnand** [comment]
I think the "many" is short for "more than 2? woah, that's too many to count".

Why do you prefer "number"?

**Comment by asakaev** [comment]
I like "many" a lot. It's very clear, but zero and negative numbers do not match "many" definition.

**Comment by dwijnand** [comment]
Ah, I see your point.  Perhaps "other", then.

And maybe even mention the fact that the int returned by `Random.nextInt(10)` is known to be between 0 and 10, but that's not in the type?

**Comment by asakaev** [comment]
Exactly what is needed!

**Pull request merged**
