### PR TITLE
Fix a typo in Scala 3 Book / Domain Modeling / FP Modeling

### PR DESCRIPTION
**Pull request by genghis-yang**
Duplicated `us` :hand_over_mouth:

### CODE REVIEW

**Comment by Philippus** [comment]
I think the original sentence was correct. There's only one `us`, and one `use`.

**Comment by genghis-yang** [comment]
I believe `Let's us use ...` = `Let us us use ...`
Have I misunderstood anything? 🤔

**Comment by Philippus** [comment]
Ah yes, you're right, I missed the apostrophe. I think that should be removed so it becomes `It ... lets us use`.

**Review by Philippus — APPROVED** [review]

**Comment by Philippus** [comment]
The build failure is unrelated to this PR.

Thanks @genghis-yang !

**Pull request merged**
