### PR TITLE
bugfix

### PR DESCRIPTION
**Pull request by rebekah**
The examples didn't make sense to me... so I played with them a bit realized they were broken and talked with @BalmungSan on discord. He suggested this resolution, which seems concise and appropriate. Here is the code in working(and tested) examples: https://github.com/rebekah/scala-3-play/blob/main/src/main/scala/ExploreContextBounds.scala

### CODE REVIEW

**Comment by julienrf** [comment]
I think it would be better to provide the definition of `max`. I believe the current code does work if `max` is defined as follows:

~~~ scala
def max[A](using Ord[A]): (A, A) => A =
  (a1, a2) => if a1 > a2 then a1 else a2
~~~

**Comment by BalmungSan** [comment]
@julienrf yeah totally, when I looked at the page I was really lost since I didn't find `max` and the code didn't make sense to me at all.
I assume it was defined before but I didn't want to check multiple pages to find out.

**Comment by rebekah** [comment]
> ```scala
> def max[A](using Ord[A]): (A, A) => A =
>   (a1, a2) => if a1 > a2 then a1 else a2
> ```

@julienrf This max method doesn't appear to use the Ord instance in any way. Am I missing something? Furthermore, when I try to use this code I get the error: ``` value > is not a member of A, but could be made available as an extension method```

**Comment by rebekah** [comment]
> > ```scala
> > def max[A](using Ord[A]): (A, A) => A =
> >   (a1, a2) => if a1 > a2 then a1 else a2
> > ```
> 
> @julienrf This max method doesn't appear to use the Ord instance in any way. Am I missing something? Furthermore, when I try to use this code I get the error: ` value > is not a member of A, but could be made available as an extension method`

**Comment by BalmungSan** [comment]
@rebekah so the funny thing is that both parts of your question are connected :)
Such `max` method should be indeed using `Ord`, specifically by the use of `>` which should be added as an extension method to any value of type `A` given the presence of the `Ord[A]`

But, it is not doing that because that code is also missing an import like:

```scala
import scala.math.Ordering.Implicits._
```

So, the lesson of the day is that code examples in docs should be complete and compiled, otherwise they may confuse newcomers reading them; which is exactly the opposite of what a doc should do :)

**Comment by julienrf** [comment]
I 100% agree with you @rebekah. That page about context bounds explains the syntax that is handled by the compiler, and in some sense we don’t _need_ to know what the definition of `max` or `Ord` is to understand the syntactic transformation performed by the compiler, but I agree that it would be way better to provide a self-contained, executable, example. I propose the following, then.

Scala 3:

~~~ scala
trait Ord[A]:
  /** @return true if a1 is greater than a2, false otherwise */
  def greaterThan(a1: A, a2: A): Boolean

/** @return the maximum value between a1 and a2 */
def max[A](a1: A, a2: A)(using ord: Ord[A]): A =
  if ord.greaterThan(a1, a2) then a1 else a2

/** @return the maximum element in a collection */
def maxElement[A](as: List[A])(using ord: Ord[A]): A =
  as.reduceLeft(max(_, _)(using ord))
~~~

Note that since the `ord` parameter is a context parameter, we don’t need to pass it explicitly to the `max` method:

~~~ scala
def maxElement[A](as: List[A])(using Ord[A]): A =
  as.reduceLeft(max(_, _))
~~~

Note that since we don’t explicitly use that context parameter, we don’t even need to give it name (that sentence does not apply to Scala 2).

In that case, we can shorten the syntax even further by using a context bound:

~~~ scala
def maxElement[A: Ord](as: List[A]): A =
  as.reduceLeft(max(_, _))
~~~

And, optionally, even further:

~~~ scala
def maxElement[A: Ord](as: List[A]): A =
  as.reduceLeft(max)
~~~

In this last form, we replace the function literal `max(_, _)` with the _eta-expansion_ of the method `max`. (This is not really related to the usage of context bounds).

Scala 2:

~~~ scala
trait Ord[A] {
  def greaterThan(a1: A, a2: A): Boolean
}

def max[A](a1: A, a2: A)(implicit ord: Ord): A =
  if (ord.greaterThan(a1, a2)) a1 else a2

def maxElement[A](as: List[A])(implicit ord: Ord[A]): A =
  as.reduceLeft(max(_, _)(ord))
~~~

Or:

~~~ scala
def maxElement[A: Ord](as: List[A]): A =
  as.reduceLeft(max(_, _))
~~~

Or even:

~~~ scala
def maxElement[A: Ord](as: List[A]): A =
  as.reduceLeft(max[A])
~~~

We should also add a note that in practice there is already a trait `Ordering[A]` in the standard library, which provides a methods `max`, and there is already a method `max` on `List`.

**Comment by rebekah** [comment]
@julienrf Wow, yes that would be fantastic!

**Comment by rebekah** [comment]
thank you

**Comment by julienrf** [comment]
Thank _you_ for starting this discussion!

**Comment by rebekah** [comment]
@julienrf you are welcome!

**Pull request merged**
