### PR TITLE
The correct syntax of fixed

### PR DESCRIPTION
**Pull request by scyber**

### CODE REVIEW

**Comment by scyber** [comment]
This is a correct syntax apply of function to the List.

**Comment by martijnhoekstra** [comment]
I recently re-wrote the English version of that page, to make that part specifically clearer: https://docs.scala-lang.org/tour/multiple-parameter-lists.html

That part is meant to illustrate the signature that doesn't work, but doesn't do so very clearly.

**Comment by SethTisue** [comment]
@scyber interested in updating the translation to match the new text?

**Comment by SethTisue** [comment]
closing for inactivity, happen to reopen if activity resumes

**Pull request closed without merging**
