### PR TITLE
Correction in sentence

### PR DESCRIPTION
**Pull request by Gurpreet-Singh-Bhupal**

### CODE REVIEW

**Comment by som-snytt** [comment]
This is not a correction, but a change in "style," so to speak.

To change it would require approval by the SIP committee, which manages all Syntax Interjection Proposals.

Both resources present a typographical origin story:
https://style.mla.org/punctuation-and-quotation-marks/
https://www.quickanddirtytips.com/education/grammar/how-to-use-quotation-marks

Recommend @SethTisue close with prejudice.

**Comment by sjrd** [comment]
Given that we're in October in half of the world already. This is probably [Hacktoberfest spam](https://hacktoberfest.digitalocean.com/faq/).

**Comment by SethTisue** [comment]
in the traditional way of punctuating that I learned in school, the comma does go inside the double quotes, even though THE OBVIOUS ILLOGICALITY OF THIS DRIVES PROGRAMMERS INSANE

**Comment by som-snytt** [comment]
@SethTisue No one corrected my syntax pun when I wrote "style," however.

Since no-one corrected me to-day, we are probably safe in our conventions, but as you comment elsewhere, it's helpful to have the issue thoroughly documented.

I'm reminded now to submit my PRs changing "artefact" to "artifact."

**Pull request closed without merging**
