### PR TITLE
Expanded the learning.html page and added new course materials

### PR DESCRIPTION
**Pull request by Madusudanan**
1) Expanded the learning section by including links for all individual courses in the Coursera Scala specialization
2) Included Dr.Mark C Lewis course videos from youtube
3) Added a note about Coursera paid version for clarity

### CODE REVIEW

**Comment by SethTisue** [comment]
I've seen some confusion in the community about the Coursera free vs paid issue, so I like how this PR adds a bit of extra explanation about that.

**Comment by SethTisue** [comment]
note that for this to be mergeable, the info on the Lewis courses would need to be under its own header, not under the Coursera/EPFL header

**Comment by Madusudanan** [comment]
Added a header for Lewis courses

**Comment by heathermiller** [comment]
Thank you @Madusudanan!! This looks good to me!

**Pull request merged**
